# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main", "ci" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  SCIAGENT_CI_DATA_DIR: /local/sciagent_ci_data/

permissions:
  contents: read

jobs:
  lint:
    defaults:
      run:
        shell: bash -l {0}

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Create environment
        id: create_env
        run: |
          uv venv --python 3.11 .venv_lint
          source .venv_lint/bin/activate

      - name: Install Ruff
        run: |
          source .venv_lint/bin/activate
          uv pip install ruff

      - name: Run Ruff
        run: |
          source .venv_lint/bin/activate
          ruff check src/ --output-format=github

      - name: Remove environment
        if: always()
        run: |
          source .venv_lint/bin/deactivate
          rm -rf .venv_lint

  linux-x86-gpu:

    defaults:
      run:
        shell: bash -l {0}

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Update test data
        id: update_test_data
        run: |
          PACKAGE_DIR=$(pwd)
          cd $SCIAGENT_CI_DATA_DIR
          git pull origin main
          cd $PACKAGE_DIR

      - name: Create environment
        id: create_env
        run: |
          uv venv --python 3.11 .venv_pytest
          source .venv_pytest/bin/activate
        
      - name: Install dependencies
        run: |
          source .venv_pytest/bin/activate
          uv pip install --upgrade pip
          uv pip install pytest
          uv pip install -r requirements.txt
          uv pip install -e .

      - name: List build environment
        run: |
          source .venv_pytest/bin/activate
          uv pip list

      - name: Test with pytest
        run: |
          source .venv_pytest/bin/activate
          echo $(which python)
          cd tests
          pytest -s --high-tol

      - name: Remove environment
        if: always()
        run: |
          source .venv_pytest/bin/deactivate
          rm -rf .venv_pytest
